### ISSUE TITLE
micro_ros_utilities/type_utilities.h: No such file or directory

### ISSUE THREAD

**Issue by hwacoding** [linorobot/linorobot2_hardware#13]

**Comment by grassjelly** [comment]
hey @hwacoding do you mind sharing what caused the problem?

**Comment by hwacoding** [comment]
Already solved it. Thanks

**Comment by grassjelly** [comment]
hey @hwacoding . Could you share how it was solved please in case other users face the same problem.

**Comment by adityasivaraj** [comment]
Hey @hwacoding , I am also facing the same issue, could you let me know how you solved it?

**Comment by hwacoding** [comment]
oh sorry, I am late.
firmware/platformio.ini
I add lib_deps =  https://github.com/micro-ROS/micro_ros_utilities

And, we need rosidl.
https://github.com/ros2/rosidl
I install these in my computer.
And paste it firmware/.pio/libdeps/teensy40

**Comment by adityasivaraj** [comment]
hey @hwacoding , Thank you for getting back. Both of these changes in robot computer?

**Comment by adityasivaraj** [comment]
Also, for some reason rosidl is not recognized at all by platformio... could you tell me how do you install rosidl?

**Comment by grassjelly** [comment]
I can't replicate this problem. @adityasivaraj could you totally remove your linorobot2_hardware, clone and reinstall the firmware?

**Comment by adityasivaraj** [comment]
Hey @grassjelly , so I think I solved the problem. I added micro_ros_utilities as mentioned in [here](https://github.com/linorobot/linorobot2_hardware/issues/13#issuecomment-1173432705). Then I cloned the foxy build of rosidl into linorobot2_ws/src, then rosdep install --from-paths src -y --ignore-src. colcon build after that, and copy rosidl/rosidl_typesupport_introspect_c folder to firmware/.pio/libdeps/teensy31/. This seemingly works for pio upload. But now teleop commands are not working, and I am not sure if the two are related.

Did this problem occur because I cloned linorobot2_hardware in linorobot2_ws/src? The instructions were not clear on where to install this repo.

**Comment by grassjelly** [comment]
managed to replicate the error in Foxy. You can have linorobot2_hardware anywhere. Let me take a look at this one. Meanwhile, have you considered moving to galactic?

Could you try if setting this line https://github.com/linorobot/linorobot2_hardware/blob/master/firmware/platformio.ini#L16 to galactic fixes all your problem?

**Comment by adityasivaraj** [comment]
> Could you try if setting this line https://github.com/linorobot/linorobot2_hardware/blob/master/firmware/platformio.ini#L16 to galactic fixes all your problem?

No, unfortunately that did not solve my issue.

> Meanwhile, have you considered moving to galactic?

Not right now, I want to develop with something that has long term support, I tried running galactic build in humble installation, but that had a lot of dependency issues...

**Comment by grassjelly** [comment]
hey @adityasivaraj could you try the recent commits on foxy branch. Added new installation guide here: https://github.com/linorobot/linorobot2_hardware#2-download-linorobot2_hardware

**Comment by adityasivaraj** [comment]
Hey @grassjelly , Yes this works! Although there maybe a problem with the calibration firmware upload, I am not sure if I screwed up while installing, but, when I copied the .pio folder from the main firmware folder to calibration folder, it worked fine.
